### ISSUE TITLE
Where to get "train.npy"、"val.npy"、"test.npy"

### ISSUE THREAD

**Issue by yy19931029** [mysee1989/TCAE#5]
hello, Where to get "train.npy"、"val.npy"、"test.npy"？THX

**Comment by mysee1989** [comment]
"train.npy"、"val.npy"、"test.npy" refer to the numpy array that contain the names of subjects for training/testing/validation.
I have added a python script (dataset_split.py) that generate the three files("train.npy"、"val.npy"、"test.npy").

Besides, I have added the detailed description about how to prepare dataset for training.

**Comment by yy19931029** [comment]
OK! Thank you!
