### ISSUE TITLE
How to test my model?

### ISSUE THREAD

**Issue by yy19931029** [mysee1989/TCAE#7]
Hello, thanks for your help, I successfully trained my model, that is a .pth file, but I don't know how to use it to get the head embedding and AU embedding,  I read your paper, the result of AU and pose is a list in size of 1 * 1 * 256, how to switch it into AUs and pose.

**Comment by mysee1989** [comment]
You can obtain the AU/pose embedding according to the encoder. 
After the training process, you only need the encoder. 
I'll add the description and the python script for testing.

**Comment by yy19931029** [comment]
Oh, thank you! I finish training my encoder and wish your code~

**Comment by yy19931029** [comment]
Thank you very much!

**Comment by yy19931029** [comment]
Hello, can you tell me how to transform the AU from size of 1 * 1 * 256 to AUs, thank you~

**Comment by mysee1989** [comment]
Given an input facial image, you can obtain the 'emotion_feature' from the trained TCAE model.

The original size of 'emotion_feature'  is 1 * 1 * 256, just squeeze it to 256. 
Then train the AU classifier.
